import path from "node:path";

import type { DiagramSpec } from "./diagramspec-topology.js";
import type {
  RepoWorkflowArtifactOutput,
  RepoWorkflowArtifactOutputFormat,
} from "./repo-workflow-config.js";

export interface MarkdownEmbedReferencedArtifact {
  format: RepoWorkflowArtifactOutputFormat;
  path: string;
}

export function createMarkdownEmbedReferences(options: {
  outputs: readonly RepoWorkflowArtifactOutput[];
  resolvePath(output: RepoWorkflowArtifactOutput): string;
}): MarkdownEmbedReferencedArtifact[] {
  return options.outputs
    .filter((output) => output.format !== "markdown")
    .map((output) => ({
      format: output.format,
      path: options.resolvePath(output),
    }));
}

function normalizePathForMarkdown(filePath: string): string {
  return filePath.split(path.sep).join("/");
}

function markdownRelativePath(fromPath: string, toPath: string): string {
  const relativePath = normalizePathForMarkdown(
    path.relative(path.dirname(fromPath), toPath),
  );

  return relativePath === "" ? path.basename(toPath) : relativePath;
}

function markdownText(value: string): string {
  return value.replace(/\\/gu, "\\\\").replace(/\[/gu, "\\[").replace(/\]/gu, "\\]");
}

const artifactLabels: Record<RepoWorkflowArtifactOutputFormat, string> = {
  d2: "D2",
  dot: "DOT",
  markdown: "Markdown",
  mermaid: "Mermaid",
  png: "PNG",
  svg: "SVG",
};

function artifactLabel(format: RepoWorkflowArtifactOutputFormat): string {
  return artifactLabels[format];
}

function primaryImageReference(
  references: readonly MarkdownEmbedReferencedArtifact[],
): MarkdownEmbedReferencedArtifact | undefined {
  return (
    references.find((reference) => reference.format === "svg") ??
    references.find((reference) => reference.format === "png")
  );
}

function imageLines(options: {
  title: string;
  embedPath: string;
  reference: MarkdownEmbedReferencedArtifact | undefined;
}): string[] {
  if (options.reference === undefined) {
    return [];
  }

  return [
    `![${options.title}](${markdownRelativePath(
      options.embedPath,
      options.reference.path,
    )})`,
  ];
}

function linkLines(options: {
  embedPath: string;
  references: readonly MarkdownEmbedReferencedArtifact[];
}): string[] {
  return options.references.map(
    (reference) =>
      `- [${artifactLabel(reference.format)} artifact](${markdownRelativePath(
        options.embedPath,
        reference.path,
      )})`,
  );
}

function imageLinkSeparator(
  imageLines: readonly string[],
  linkedReferences: readonly MarkdownEmbedReferencedArtifact[],
): string[] {
  if (imageLines.length === 0 || linkedReferences.length === 0) {
    return [];
  }

  return [""];
}

export function createMarkdownEmbedContent(options: {
  spec: DiagramSpec;
  embedPath: string;
  references: readonly MarkdownEmbedReferencedArtifact[];
}): string {
  const title = markdownText(options.spec.title);
  const imageReference = primaryImageReference(options.references);
  const embeddedImageLines = imageLines({
    title,
    embedPath: options.embedPath,
    reference: imageReference,
  });
  const linkedReferences = options.references.filter(
    (reference) => reference !== imageReference,
  );
  const lines = [
    "<!-- Generated by DiagramPilot. Do not edit by hand. -->",
    "",
    `# ${title}`,
    "",
    ...embeddedImageLines,
    ...imageLinkSeparator(embeddedImageLines, linkedReferences),
    ...linkLines({
      embedPath: options.embedPath,
      references: linkedReferences,
    }),
    "",
  ];

  return lines.join("\n");
}
